# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:36
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url_pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='settings.MEDIA_ROOT/pdfs/1.pdf', storage=django.core.files.storage.FileSystemStorage(location=b'C:/Users/andre/PycharmProjects/OnlineLibrary/media/'), upload_to='pdfs'),
        ),
    ]
