# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 22:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20180418_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(1, 'Premium'), (2, 'Standard')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(1, 'Art'), (2, 'Fantasy'), (3, 'Biographies'), (4, 'Science'), (5, 'Romance'), (6, 'Religion'), (7, 'Children'), (8, 'History')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'C:/Users/andre/PycharmProjects/OnlineLibrary/media/'), upload_to='pdfs'),
        ),
    ]
