# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 12:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20180420_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'C:\\Users\\andre\\PycharmProjects\\OnlineLibraryProject\\media'), upload_to='pdfs'),
        ),
    ]
