# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20180420_1522'),
        ('library_app', '0005_profile'),
    ]

    operations = [
    ]
